### ISSUE TITLE
Support for php 8.1

### ISSUE THREAD

**Issue by federicoemartinez** [MonetDB/MonetDB-PHP#4]
Hi!
I would like to know if you have plans to support MonetDB-PHP for php 8.1.
I see that there hasn't been any activity this year and I would like to know the status of the project.

Thanks!

**Comment by bolner** [comment]
It will support it after the weekend.

**Comment by bolner** [comment]
@federicoemartinez Hi, the PHP versions 8.x are now supported by the newest version of the library: 1.2.1

You can upgrade to it with:
```
composer require tbolner/monetdb-php
```
